
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deasam-app
spec:
  replicas: 4
  selector:
    matchLabels:
      name: deasam-nodeapp
  template:
    metadata:
      labels:
        name: deasam-nodeapp
    spec:
      containers:
      - name: deasam-nodeapp
        image: deasam/i-deepaksharma09-master:v1
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: conf
          - secretRef:
              name: secretdetail
        env:
          - name: PORT
            value: "8080"
