
apiVersion: v1
kind: Service
metadata:
  name: deasam-lb
  namespace: deasam-ns
spec:
  type: LoadBalancer
  selector:
    name: deasam-nodeapp
  ports:
  - port: 80
    targetPort: 8080
